version: 2.1

refs:
  container: &container
    docker:
      - image: node:lts-alpine
    working_directory: ~/repo
  steps:
    - &Versions
      run:
        name: Versions
        command: node -v && yarn -v
    - &Prepare
      run:
        name: Prepare for build
        command: apk add ca-certificates git
    - &Install
      run:
        name: Install Dependencies
        command: yarn install --pure-lockfile
    - &StoreDep
      save_cache:
        key: v1-node-modules-{{ arch }}-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules
    - &RestoreDep
      restore_cache:
        key: v1-node-modules-{{ arch }}-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules
    - &Build
      run:
        name: Build
        command: yarn build
    - &Lint
      run:
        name: Lint
        command: yarn lint
    - &Test
      run:
        name: Test
        command: yarn test
    - &Release
      run:
        name: Release
        command: yarn release

jobs:
  build:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Prepare
      - *RestoreDep
      - *Install
      - *StoreDep
      - *Build
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - esm

  test:
    <<: *container
    steps:
      - checkout
      - *Prepare
      - *RestoreDep
      - attach_workspace:
          at: .
      - *Test

  lint:
    <<: *container
    steps:
      - checkout
      - *Prepare
      - *RestoreDep
      - attach_workspace:
          at: .
      - *Lint

  deploy:
    <<: *container
    steps:
      - checkout
      - *Prepare
      - *RestoreDep
      - attach_workspace:
          at: .
      - run:
          name: Setup GitHub
          command: |
            git config --global user.email "wisteria.r.s@gmail.com"
            git config --global user.name "rswisteria"
            git remote rm origin
            git remote add origin https://${GITHUB_TOKEN}@github.com/rswisteria/useReactMediaQuery
      - *Release

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - deploy:
          context: common-env-vars
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
